version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_medpro
    environment:
      MYSQL_DATABASE: medpro_api
      MYSQL_ROOT_PASSWORD: aluno
      MYSQL_USER: root
      MYSQL_PASSWORD: aluno
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: .
    container_name: medpro_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/medpro_api?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: aluno
    depends_on:
      - mysql

volumes:
  mysql_data:
